### ISSUE TITLE
Questions new user

### ISSUE THREAD

**Issue by remybonnav** [nadeemlab/ImPartial#10]
Hi, thanks for this great model.
However I have some questions.

How do you provide multi class labels groundtruths? Do you use different grayscale level on a single image to represent the different labels or for each image of training one need a groundtruth image for each label (1 for nuclei and 1 for cytoplasm).

Which input image size does one need? i believe 512*512 but can it be bigger?

Why does one need to build the Fiji plugin locally and you don't provide directly the Fiji Plugin from Update site?

Thanks a lot for your help.

**Comment by sanadeem** [comment]
Thanks Remy. Great questions! For multi class ground truth labels, we are leaning towards single whole-cell label (given any number of channels) similar to automatic DL DeepCell/Mesmer or Cellpose Cyto models (though we do provide option for individual labels too per channel which as you can imagine is slightly more tedious). Again this is an interactive DL model, so you will create the ground truth labels as you go.

The nice thing about ImPartial is you can go as big as you want or as your GPU allows (1024, 2048, 4096,…).

We are still finalizing/optimizing the plugin/training time with NVIDIA team so we haven’t officially released the Fiji Plugin yet. Once we finalize this version, we will definitely release the Plugin on the Update site too.
