### ISSUE TITLE
sample images for using Fiji plugin

### ISSUE THREAD

**Issue by hw-ju** [nadeemlab/ImPartial#12]
Hi!
Could you point me to some sample digital pathology images to download so that I can try out the Fiji plugin? My own current data is in .svs format and can't be opened by Fiji.

**Comment by gunjan-sh** [comment]
Hi, 

You can use [Vectra_WC_2CH_tiff](https://github.com/nadeemlab/ImPartial/tree/main/Data/Vectra_WC_2CH_tiff) sample dataset from the data folder to try out on Fiji. 

To start monai server, please refer these instructions : https://github.com/nadeemlab/ImPartial#monai-label 

Example command for sample dataset:
monailabel start_server -a api -s ~/Data/Vectra_WC_2CH_tiff/

After you start Fiji and open ImPartial plugin, connect the plugin to your host ip address ( http://localhost:8000/). The dataset sample images & roi's from the monai server will be loaded.
