### ISSUE TITLE
demo for Fiji plugin

### ISSUE THREAD

**Issue by hw-ju** [nadeemlab/ImPartial#13]
Hi!
If you could have a demo recording showing how to use Fiji plugin and MONAI Label server (especially the DeepEdit interactive annotation functionality), that would be great!

**Comment by gunjan-sh** [comment]
Hi,
 
The Impartial Fiji plugin currently only support our ImPartial whole cell segmentation model. 
We will soon be sharing a detailed demo for Impartial plugin.
