### ISSUE TITLE
Plugin Error while running Inference 

### ISSUE THREAD

**Issue by gunjan-sh** [nadeemlab/ImPartial#26]
While running inference, the plugin gives a 504 error. Error pops up after Infer runs on a few images and then stops. Error is independent of the image. The behavior is random, but able to reproduce on .png format images on cloud server. Typically seeing this if dataset has more than 8-9 images.  Error is only seen on Cloud server not on local deployment.

**Comment by wooferclaw** [comment]
I have added additional logging, that pointed me to synchronisation problems during inference request processing.

After that i haver added a mutex to ImPartial Plugin UI process to handle the inference result responses in the Fiji UI thread.
It seems to fix the issue for any number of infered images.

**Comment by wooferclaw** [comment]
@gunjan-sh  Please check PR #28 for the fixes. If it is OK - we can merge.

**Comment by gunjan-sh** [comment]
@wooferclaw Ran Impartial on couple of datasets, with the fix. For me the images are not getting uploaded. Getting following error everytime :

<img width="258" alt="error-uploading-images" src="https://github.com/nadeemlab/ImPartial/assets/19653577/b89cb0e6-df71-45b4-b7f5-e801fa5f00b6">
